//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace course_project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Guild
    {
        public Guild()
        {
            this.Machine = new HashSet<Machine>();
        }
    
        public int id_guild { get; set; }
        [Required]
        [StringLength(30)]
        public string nameGuild { get; set; }
        [Required]
        [StringLength(40)
        public string firmGuild { get; set; }
    
        public virtual ICollection<Machine> Machine { get; set; }
    }
}
